apiVersion: dnsmasq.kvaps.cf/v1beta1
kind: DhcpPool
metadata:
  name: test-pool
spec:
  controller: ""
  pools:
  - rangeStart: "10.0.0.100"
    rangeEnd: "10.0.0.200"
    netmask: "255.255.255.0"
    leaseTime: "12h"
