image:
  repository: ghcr.io/natchikhin/dnsmasq-controller
  tag: ""
  pullPolicy: IfNotPresent

crds:
  install: true

serviceAccount:
  create: true
  name: ""
  annotations: {}

controller:
  name: ""
  watchNamespace: ""
  metricsAddr: ":8080"
  logLevel: ""
  syncDelay: ""
  confDir: ""
  cleanup: false

dns:
  enabled: true
  replicas: 1
  metricsAddr: ""
  args: []
  resources: {}
  nodeSelector:
    node-role.kubernetes.io/dnsmasq: ""
  tolerations: []
  env: []

dhcp:
  enabled: false
  replicas: 1
  metricsAddr: ":8081"
  leaderElection: true
  args:
    - "--dhcp-broadcast"
    - "--dhcp-authoritative"
    - "--dhcp-leasefile=/dev/null"
  resources: {}
  nodeSelector:
    node-role.kubernetes.io/dnsmasq: ""
  tolerations: []
  env: []

priorityClassName: system-node-critical

podAnnotations: {}

podLabels: {}
