{{- if and (not .Values.serviceAccount.create) (not .Values.serviceAccount.name) -}}
{{- fail "serviceAccount.name must be set when serviceAccount.create=false" -}}
{{- end -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "dnsmasq-controller.fullname" . }}
  labels:
    {{- include "dnsmasq-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "dnsmasq-controller.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "dnsmasq-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
