{{- if .Values.dns.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dnsmasq-controller.fullname" . }}-dns
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dnsmasq-controller.labels" . | nindent 4 }}
    app.kubernetes.io/component: dns
spec:
  replicas: {{ .Values.dns.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "dnsmasq-controller.selectorLabels" . | nindent 6 }}
      role: dns
  template:
    metadata:
      labels:
        {{- include "dnsmasq-controller.selectorLabels" . | nindent 8 }}
        role: dns
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: {{ include "dnsmasq-controller.serviceAccountName" . }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      containers:
        - name: dnsmasq-controller
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
          image: "{{ .Values.image.repository }}:{{ include "dnsmasq-controller.imageTag" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --dns
            {{- if .Values.controller.name }}
            - --controller={{ .Values.controller.name }}
            {{- end }}
            {{- if .Values.controller.watchNamespace }}
            - --watch-namespace={{ .Values.controller.watchNamespace }}
            {{- end }}
            {{- if .Values.controller.metricsAddr }}
            - --metrics-addr={{ .Values.controller.metricsAddr }}
            {{- end }}
            {{- if .Values.controller.logLevel }}
            - --log-level={{ .Values.controller.logLevel }}
            {{- end }}
            {{- if .Values.controller.syncDelay }}
            - --sync-delay={{ .Values.controller.syncDelay }}
            {{- end }}
            {{- if .Values.controller.confDir }}
            - --conf-dir={{ .Values.controller.confDir }}
            {{- end }}
            {{- if .Values.controller.cleanup }}
            - --cleanup
            {{- end }}
            {{- if .Values.dns.args }}
            - "--"
            {{- range .Values.dns.args }}
            - {{ . | quote }}
            {{- end }}
            {{- end }}
          {{- with .Values.dns.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.dns.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.dns.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dns.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
